import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — DecodeCoverage",
  description:
    "Terms and conditions for using the DecodeCoverage policy decoder service.",
};

export default function TermsPage() {
  return (
    <>
      <nav>
        <div className="nav-inner">
          <a href="/" className="logo">
            Decode<span>Coverage</span>
          </a>
          <a href="/#upload" className="nav-cta">
            Upload My Policy
          </a>
        </div>
      </nav>

      <main className="legal-page">
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: March 10, 2026</p>

        <section>
          <h2>Service Description</h2>
          <p>
            DecodeCoverage is a free AI-powered homeowners insurance policy
            decoder. You upload your insurance policy, and our system analyzes it
            to help you understand your coverage, identify potential gaps, and
            make informed decisions about your insurance.
          </p>
        </section>

        <section>
          <h2>Educational Purpose Only</h2>
          <p>
            <strong>
              DecodeCoverage is an educational tool, not a licensed insurance
              advisor.
            </strong>
          </p>
          <ul>
            <li>
              The analysis provided is for <strong>informational and
              educational purposes only</strong>.
            </li>
            <li>
              Our reports do <strong>not constitute insurance advice</strong>,
              legal advice, or professional recommendations.
            </li>
            <li>
              You should consult with a licensed insurance professional before
              making any changes to your coverage.
            </li>
            <li>
              We are <strong>not a licensed insurance broker, agent, or
              adjuster</strong>.
            </li>
          </ul>
        </section>

        <section>
          <h2>No Guarantee of Accuracy</h2>
          <p>
            Our analysis is generated by artificial intelligence and may contain
            errors or omissions. While we strive for accuracy:
          </p>
          <ul>
            <li>
              AI-generated analysis may misinterpret policy language or miss
              important provisions.
            </li>
            <li>
              Coverage determinations depend on factors beyond what appears in
              your policy document.
            </li>
            <li>
              Policy scores and risk assessments are approximate and should not
              be relied upon as definitive.
            </li>
            <li>
              We do not guarantee the completeness or accuracy of any analysis.
            </li>
          </ul>
        </section>

        <section>
          <h2>Your Responsibilities</h2>
          <p>By using DecodeCoverage, you agree to:</p>
          <ul>
            <li>
              Upload only insurance policy documents that you are authorized to
              share.
            </li>
            <li>Provide accurate contact information if you choose to connect with an advisor.</li>
            <li>
              Not use the service for any unlawful purpose or to upload harmful
              content.
            </li>
            <li>
              Verify any findings with a licensed insurance professional before
              acting on them.
            </li>
          </ul>
        </section>

        <section>
          <h2>Intellectual Property</h2>
          <p>
            The DecodeCoverage platform, including its AI analysis engine,
            design, and branding, is the property of 4Margin, LLC. Your uploaded
            documents and personal data remain your property. We claim no
            ownership over your insurance policy documents or personal
            information.
          </p>
        </section>

        <section>
          <h2>Advisor Connections</h2>
          <p>
            If you choose to connect with an advisor through our platform:
          </p>
          <ul>
            <li>
              We connect you with licensed, independent insurance professionals.
              We do not employ or control these advisors.
            </li>
            <li>
              Any advice, recommendations, or services provided by connected
              advisors are their responsibility, not ours.
            </li>
            <li>
              There is no cost or obligation to you for the initial connection.
            </li>
          </ul>
        </section>

        <section>
          <h2>Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, DecodeCoverage and 4Margin,
            LLC shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages arising from your use of the
            service. This includes, but is not limited to, damages arising from:
          </p>
          <ul>
            <li>Reliance on any analysis or report generated by our service.</li>
            <li>Errors or omissions in AI-generated content.</li>
            <li>
              Actions taken or not taken based on our coverage analysis.
            </li>
            <li>
              Interactions with insurance advisors connected through our
              platform.
            </li>
          </ul>
          <p>
            Our total liability for any claim shall not exceed the amount you
            paid to use the service (which is $0, as the service is free).
          </p>
        </section>

        <section>
          <h2>Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the
            laws of the State of Maryland, without regard to its conflict of law
            provisions.
          </p>
        </section>

        <section>
          <h2>Changes to These Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. Changes will
            be posted on this page with an updated date. Continued use of the
            service after changes constitutes acceptance of the modified Terms.
          </p>
        </section>

        <section>
          <h2>Contact Us</h2>
          <p>
            Questions about these Terms? Email us at{" "}
            <a href="mailto:support@decodecoverage.com">
              support@decodecoverage.com
            </a>
          </p>
        </section>

        <p className="legal-branding">
          Powered by{" "}
          <a href="https://4margin.com">4Margin</a>
        </p>
      </main>

      <footer>
        <div className="footer-inner">
          <div className="footer-copy">
            &copy; 2026 DecodeCoverage. Not a licensed insurance broker or
            agent. Powered by{" "}
            <a
              href="https://4margin.com"
              style={{ color: "var(--accent)", textDecoration: "none" }}
            >
              4Margin
            </a>
          </div>
          <div className="footer-links">
            <a href="/privacy">Privacy Policy</a>
            <a href="/terms">Terms of Service</a>
            <a href="mailto:support@decodecoverage.com">Contact</a>
          </div>
        </div>
      </footer>
    </>
  );
}
