import { AlertTriangle } from "lucide-react";

/**
 * Legal disclaimer for all policy analysis output.
 * Must appear on every page/component that displays policy data.
 */
export function PolicyDisclaimer({ compact }: { compact?: boolean }) {
  if (compact) {
    return (
      <p className="text-[10px] text-muted-foreground/60 leading-snug">
        Educational policy summary only — not insurance, legal, or professional
        advice. Consult a licensed public adjuster or attorney for claim-specific
        guidance.
      </p>
    );
  }

  return (
    <div className="flex items-start gap-2 rounded-md border border-slate-200 bg-slate-50 p-3 mt-2">
      <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-slate-400" />
      <p className="text-[11px] leading-relaxed text-slate-500">
        <strong className="text-slate-600">Educational Policy Summary</strong> —
        This analysis is generated by AI and is provided for educational
        purposes only. It does not constitute insurance advice, legal advice, or
        a professional policy review. Coverage determinations are made solely by
        the insurance carrier. Consult a licensed public adjuster or attorney for
        claim-specific guidance.
      </p>
    </div>
  );
}
